name: CD

on:
  push:
    tags: 
      # - "v[0-9]+.[0-9]+.[0-9]+"
      - "*"

env:
  GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  REPO: ${{ github.repository }}

jobs:
  build-tdlib:
    uses: ./.github/workflows/build-tdlib.yml
  release:
    runs-on: ubuntu-latest
    needs: build-tdlib
    steps:
      - name: Download artifacts
        run: gh run download ${{ github.run_id }} -R $REPO
      - name: Zip artifacts
        run: find * -maxdepth 0 -type d -execdir mv '{}' tdlib \; -execdir zip -r -m -6 '{}.zip' 'tdlib' \;
      - name: Create release
        run: gh release create ${{ github.ref_name }} -R $REPO --generate-notes ./*.zip
      # cargo publish